AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Enabled: false

Metrics:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false