name: CI

on: [ push, pull_request ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install igraph dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cmake make gcc g++ libxml2-dev
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Build igraph from source
        run: |
          git clone https://github.com/igraph/igraph.git
          cd igraph
          mkdir build && cd build
          cmake -DBUILD_SHARED_LIBS=ON ..
          cmake --build .
          sudo cmake --install .
      - name: Run tests
        run: bundle exec rake test

  # rubocop linting
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Run rubocop
        run: bundle exec rubocop --parallel